title: Yizheng's Blog
author: Yizheng Huang
email: huangyz0918@gmail.com
description: Generative AI, Large-scale ML, Distributed Systems, and more.
url: "https://blog.huangyz.name/"

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: Full-stack Engineer | AI Infra Researcher | UCLA
  avatar_url: avatar.jpg
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    rss: RSS
    github: huangyz0918
    linkedin: yizheng-huang
