title: Yizheng's Blog
author: Yizheng Huang
email: huangyz0918@gmail.com
description: Generative AI, Large-scale ML, Distributed Systems, and more.
url: "https://blog.huangyz.name/"

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: Hard work always pays off
  avatar_url: avatar.jpg
  date_format: "%b %d"
  back_to: "Index"
  social_links:
    rss: RSS
    github: huangyz0918
    Google Scholar: https://scholar.google.com/citations?hl=en&user=-m-3K4YAAAAJ
    linkedin: yizheng-huang
